# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

In [1]:
import numpy as np

In [2]:
simple_list=[1,2,3]
np.array(simple_list)

array([1, 2, 3])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(12,24)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [9]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones((3,7), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [14]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [17]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [18]:
np.eye(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [19]:
np.random.rand(3,5) # uniform distributed data in between 0 and 1

array([[0.85610688, 0.83258467, 0.07948187, 0.15875035, 0.93103695],
       [0.06335874, 0.95021436, 0.8185744 , 0.5991409 , 0.88945917],
       [0.64689216, 0.10142729, 0.03465424, 0.29476103, 0.80297272]])

In [20]:
np.random.rand(2,7)

array([[0.60230539, 0.41964054, 0.17107882, 0.38570936, 0.90709364,
        0.07030039, 0.39890644],
       [0.79186533, 0.56998129, 0.01494202, 0.65771496, 0.78961027,
        0.9934489 , 0.82125642]])

In [42]:
np.random.randint(2,10) # get a random number between 2 and 10 (10 excluded)

6

In [44]:
np.random.randint(20,56,10)

array([53, 20, 23, 36, 38, 55, 48, 34, 52, 49])

In [132]:
x = np.random.randint(2,7, size = (3,3))
x

array([[5, 6, 4],
       [2, 6, 3],
       [5, 5, 6]])

In [133]:
x.min()

2

In [134]:
x.argmin() 

3

In [61]:
sample_array=np.arange(16) # last digit excluded starts from 0
sample_array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
rand_array=np.random.randint(0,100,20)
rand_array

array([40, 83, 37, 55, 75, 56, 20, 14, 38, 57, 97, 25, 38, 67, 57, 13, 33,
        3, 75,  4])

In [62]:
sample_array.reshape(4,4) # if we try to reshape such that total no of elements differ in the reshaped matrix, we get error

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
rand_array.min()

3

In [51]:
rand_array.argmin() # gives position (index) of min

17

In [52]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [63]:
sample_array.shape 

(16,)

In [57]:
sample_array.reshape(2,8) # just writing this wouldn't change the shape of the array, we also need to assign it

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [58]:
sample_array =sample_array.reshape(2,8)

In [60]:
sample_array.shape

(2, 8)

In [64]:
sample_array.dtype 

dtype('int32')

In [65]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
a.T # transpose

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
a=np.random.rand(2,3) 
a

array([[0.11143751, 0.900546  , 0.50694721],
       [0.75160768, 0.41411227, 0.78529378]])

In [68]:
a.T

array([[0.11143751, 0.75160768],
       [0.900546  , 0.41411227],
       [0.50694721, 0.78529378]])

In [69]:
import numpy as np

In [70]:
sample_array=np.arange(10,21)
sample_array 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [71]:
sample_array[8]

18

In [72]:
sample_array[2:5] # slicing

array([12, 13, 14])

In [74]:
sample_array[[2,7]]

array([12, 17])

In [75]:
sample_array[1:4]=10
sample_array

array([10, 10, 10, 10, 14, 15, 16, 17, 18, 19, 20])

In [76]:
sample_array=np.arange(10,21)
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [78]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [79]:
subset_sample_array[:]=700
subset_sample_array

array([700, 700, 700, 700, 700, 700, 700])

### Two-Dimensional array

In [80]:
sample_matrix=np.array(([5,2,1,2],[4,2,1,3],[5,7,2,7]))
sample_matrix

array([[5, 2, 1, 2],
       [4, 2, 1, 3],
       [5, 7, 2, 7]])

In [81]:
sample_matrix[0][2]

1

In [82]:
sample_matrix[2,:] # colon : means all columns here

array([5, 7, 2, 7])

In [84]:
sample_matrix[1] 

array([4, 2, 1, 3])

### Custom indexing

In [86]:
sample_matrix=np.array(([30,16,18,23],[44,21,32,73],[67,76,24,71]))
sample_matrix

array([[30, 16, 18, 23],
       [44, 21, 32, 73],
       [67, 76, 24, 71]])

In [87]:
sample_matrix[:,(3,2)] 

array([[23, 18],
       [73, 32],
       [71, 24]])

###  Selection techniques

In [100]:
sample_array=np.arange(1,21)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [101]:
bool=sample_array<10
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [102]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [104]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [105]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [106]:
np.log(sample_array) # natural log (ln)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227])

In [107]:
np.max(sample_array)

20

In [109]:
np.min(sample_array)

1

In [110]:
np.argmax(sample_array)

19

In [111]:
np.argmin(sample_array)

0

In [112]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400], dtype=int32)

In [77]:
np.std(sample_array)

8.65544144839919

In [114]:
np.var(sample_array)

33.25

In [115]:
np.mean(sample_array)

10.5

In [116]:
array=np.random.randn(3,6)
array

array([[ 0.53272284, -0.03715369,  1.30709196,  1.2179284 ,  0.22427891,
         0.87739771],
       [-0.8630562 , -0.22388264,  0.38114957, -2.34389663,  0.62341189,
         0.22324359],
       [ 0.34525009,  0.38313223,  0.47922627,  0.3265506 , -1.48983127,
        -0.90203035]])

In [117]:
np.round(array,decimals=2) 

array([[ 0.53, -0.04,  1.31,  1.22,  0.22,  0.88],
       [-0.86, -0.22,  0.38, -2.34,  0.62,  0.22],
       [ 0.35,  0.38,  0.48,  0.33, -1.49, -0.9 ]])

In [118]:
sports=np.array(['golf','cricket','tennis','football'])
np.unique(sports)

array(['cricket', 'football', 'golf', 'tennis'], dtype='<U8')

# Pandas 

In [135]:
import pandas as pd

In [136]:
labels=['a','b','c','d']
list=[11,12,13,14]
array=np.array([11,12,13,14])
dict={'w':11,'x':12,'y':13,'z':14}


In [137]:
pd.Series(data=list)

0    11
1    12
2    13
3    14
dtype: int64

In [138]:
pd.Series(data=list,index=labels)

a    11
b    12
c    13
d    14
dtype: int64

In [139]:
pd.Series(array,labels)

a    11
b    12
c    13
d    14
dtype: int32

In [140]:
pd.Series(list,labels) # we get the same results

a    11
b    12
c    13
d    14
dtype: int64

In [142]:
pd.Series(dict)

w    11
x    12
y    13
z    14
dtype: int64

### Pandas dataframe and indexing

In [143]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','tennis','golf'])
sports1

cricket     1
football    2
tennis      3
golf        4
dtype: int64

In [144]:
sports1['cricket']

1

In [147]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [145]:
pd.Series([11,2,3,4],['cricket','football','baseball','golf']) 

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [148]:
sports1+sports2 # index are automatically arranged in order (a to z)

baseball     NaN
cricket     12.0
football     4.0
golf         8.0
tennis       NaN
dtype: float64

In [149]:
df1=pd.DataFrame(np.random.randn(3,5),index='A B C '.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1


Score1    Score2    Score3    Score4    Score5
A  0.897998  0.328391  0.534656 -0.269625  0.511797
B -1.069167  1.464255  0.204253 -1.162975 -0.886701
C  3.016639  1.879506  1.334072 -0.476209 -0.469360

In [150]:
df1['Score2']

A    0.328391
B    1.464255
C    1.879506
Name: Score2, dtype: float64

In [151]:
df1[['Score2','Score1']]

Score2    Score1
A  0.328391  0.897998
B  1.464255 -1.069167
C  1.879506  3.016639

In [152]:

df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.897998  0.328391  0.534656 -0.269625  0.511797  1.226389
B -1.069167  1.464255  0.204253 -1.162975 -0.886701  0.395088
C  3.016639  1.879506  1.334072 -0.476209 -0.469360  4.896145

In [153]:
df1.drop()

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [154]:
df1.reset_index()

index    Score1    Score2    Score3    Score4    Score5    Score6
0     A  0.897998  0.328391  0.534656 -0.269625  0.511797  1.226389
1     B -1.069167  1.464255  0.204253 -1.162975 -0.886701  0.395088
2     C  3.016639  1.879506  1.334072 -0.476209 -0.469360  4.896145

In [155]:
df2={'ID':['101','102','103','107','176'],'Name':['Harry','Percy','Ron','Neville','Sally'],'Profit':[20,22,56,97,123]}
df=pd.DataFrame(df2)
df

ID     Name  Profit
0  101    Harry      20
1  102    Percy      22
2  103      Ron      56
3  107  Neville      97
4  176    Sally     123

In [164]:
df3 = pd.read_csv(r"C:\Users\Rajeev\Desktop\Results.csv") # reading a csv, to read excel, we use pd.read_excel() 
df3.head()

Area   Mean    Min    Max   Perim.   Diameter          D  Circ.  \
0  1.0  805.0  255.0  255.0  255.0  107.598  17.124754  16.007481  0.874   
1  2.0    4.0  255.0  255.0  255.0    8.243   1.311914   1.128379  0.740   
2  3.0   69.0  255.0  255.0  255.0   45.556   7.250463   4.686511  0.418   
3  4.0   40.0  255.0  255.0  255.0   23.314   3.710538   3.568248  0.925   
4  5.0   81.0  255.0  255.0  255.0   36.971   5.884117   5.077706  0.745   

   %Area     AR  Round  Solidity  
0  100.0  1.283  0.779     0.975  
1  100.0  4.000  0.250     1.000  
2  100.0  4.094  0.244     0.885  
3  100.0  1.489  0.671     0.930  
4  100.0  2.199  0.455     0.931